Create de
qbcore-framework/qb-bankrobbery pull request #106
Opened 2023-01-12 22:34 UTC by Coregenetic

deutsch hinzugefügt

- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)

> **Yes**

- Does your code fit the style guidelines? [yes/no]

> **Yes**

- Does your PR fit the contribution guidelines? [yes/no]

> **Yes**

2023-05-04 18:35 UTC, GodyFromDiscord requested changes
Please rename the file to de.lua and not just de

2023-05-04 18:36 UTC, GodyFromDiscord requested changes
Update requested changes

2023-05-04 18:36 UTC, GodyFromDiscord commented on locales/de
> +Lang = Lang or Locale:new({
```
if GetConvar('qb_locale', 'en') == 'de' then
    Lang = Locale:new({
        phrases = Translations,
        warnOnMissing = true,
        fallbackLang = Lang,
    })
end
```


Please add this due to the locale system

2023-05-10 14:52 UTC, ChristianBDev commented
@Coregenetic Please Update to the requested changes so we can continue

2023-05-22 14:14 UTC, closed without merging