auto locale switching system
qbcore-framework/qb-bankrobbery pull request #98
Opened 2022-09-10 07:06 UTC by buddizer

**Describe Pull request**
adding auto switch locale system

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2022-09-12 08:31 UTC, tom-osborne requested changes

2022-09-12 08:31 UTC, tom-osborne commented on fxmanifest.lua
> +    'locales/en.lua', -- Change this to your preferred language.
Please remove the comment. There is no need for a user to switch anymore.

2022-09-13 22:10 UTC, buddizer commented
Fixed

2022-09-13 22:58 UTC, D4isDAVID approved these changes
LGTM

2022-09-14 07:57 UTC, tom-osborne approved these changes

2022-09-14 07:57 UTC, merged